[build-system]
requires = ["setuptools>=45", "wheel", "setuptools_scm>=6.2"]
build-backend = "setuptools.build_meta"

[tool.black]
target-version = ["py37"]

[tool.isort]
multi_line_output = 3
profile = "black"
float_to_top = true
known_first_party = "ufoLib2"

[tool.setuptools_scm]
write_to = "src/ufoLib2/_version.py"
